### PR TITLE
persistence bar code can be returned for a Morph object

### PR DESCRIPTION
**Pull request by Visdoom**
The Morph object now stores also its graph representation. Based on this one can calculate the persistence code of the neuron.

### CODE REVIEW

**Comment by Visdoom** [comment]
It still needs some documentation

**Comment by huangziwei** [comment]
Here are some thoughts:

* Class methods are better not to return data. 
* Processed data are better stored  in class attributes. Then a class method utilizes this processed data in the class attributes to make a plot or do something else. 

what do you think?

**Comment by Visdoom** [comment]
I see your point, and I agree your suggestions match the behaviour of the toolbox so far better.
But what if someone wants to use the data differently? 

Well, thinking about it I guess I could create a data frame that holds the type of the branch, its birth and death time and then one can filter the diagram for different subtrees (apical dendrites, axon, etc)

Bit like this:

node_id | type [int] | birth [ microns] | death [microns] |
1            | 1            | 38.4                  | 0                        |
...

What do you say?

**Comment by huangziwei** [comment]
That sounds good.  Something like self.df_persistent_barcode holds the data, and some self.show_persistent_diagram() to use the data.

**Comment by Visdoom** [comment]
` m.show_persistence_diagram()` now shows an ensemble of persistence diagram, persistence image in 1D after Wang et al and a persistence image in 2D after Kanari et al.

image

**Pull request merged**
